name: Deploy Bedrock Server

on:
  workflow_dispatch:
    inputs:
      server_name:
        description: 'Name of the Bedrock server'
        required: true
      max_players:
        description: 'Maximum number of players'
        required: true
        default: '10'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Create server directory
        run: mkdir -p server/${{ github.event.inputs.server_name }}

      - name: Download Bedrock server
        run: |
          curl -L -o server/${{ github.event.inputs.server_name }}/bedrock-server.zip https://minecraft.azureedge.net/bin-linux/bedrock-server-latest.zip
          unzip server/${{ github.event.inputs.server_name }}/bedrock-server.zip -d server/${{ github.event.inputs.server_name }}

      - name: Configure server properties
        run: |
          echo "max-players=${{ github.event.inputs.max_players }}" > server/${{ github.event.inputs.server_name }}/server.properties

      - name: Start Bedrock server
        run: |
          cd server/${{ github.event.inputs.server_name }}
          nohup ./bedrock_server > server.log 2>&1 &

      - name: Output server information
        run: |
          echo "Bedrock server '${{ github.event.inputs.server_name }}' is running."