name: Bedrock Minecraft Server

on:
  workflow_dispatch:
    inputs:
      max_players:
        description: 'Maximum number of players'
        default: '20'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create server directory
        run: mkdir -p server

      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Download Bedrock Server
        run: |
          # Download the exact version specified in SERVER_TYPES
          curl -o bedrock-server.zip "https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.10.01.zip"
          unzip bedrock-server.zip -d bedrock-server
          chmod +x bedrock-server/bedrock_server
        continue-on-error: false

      - name: Setup server properties
        run: |
          cd bedrock-server
          if [ -f "server.properties" ]; then
            sed -i "s/max-players=.*/max-players=${{ github.event.inputs.max_players }}/" server.properties
          else
            echo "max-players=${{ github.event.inputs.max_players }}" > server.properties
          fi

      - name: Start Cloudflared tunnel
        run: |
          cd bedrock-server
          cloudflared tunnel --url tcp://localhost:19132 > tunnel.log 2>&1 &
          echo "Waiting for tunnel to establish..."
          sleep 10
          # Extract and display tunnel URL
          grep -o 'tcp://.*\.trycloudflare.com' tunnel.log || echo "Failed to establish tunnel"
          cat tunnel.log

      - name: Start Bedrock Server
        run: |
          cd bedrock-server
          LD_LIBRARY_PATH=. ./bedrock_server
        env:
          MAX_PLAYERS: ${{ github.event.inputs.max_players }}