name: Minecraft Admin Panel

on:
  workflow_dispatch:
    inputs:
      timeout:
        description: 'Admin panel timeout in minutes'
        default: '60'
        required: false
      port:
        description: 'Admin panel port'
        default: '8080'
        required: false

jobs:
  run-admin-panel:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Use a fixed value here
    
    steps:
      - name: Set timeout
        run: echo "Using timeout of ${{ github.event.inputs.timeout || 60 }} minutes"
        
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pyngrok requests werkzeug jinja2 pymdown-extensions markdown
          
      - name: Download latest backups
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: minecraft-backup
          path: ./backups
          
      - name: Setup directories
        run: |
          mkdir -p admin_panel/static/css || true
          mkdir -p admin_panel/templates || true
          mkdir -p backups || true
          mkdir -p server_configs || true
          mkdir -p server_templates/vanilla || true
          mkdir -p server_templates/paper || true
          mkdir -p server_templates/forge || true
          mkdir -p server_templates/fabric || true
          mkdir -p server_templates/bedrock || true
          mkdir -p uploads || true
          
      - name: Copy dashboard template
        run: |
          # First check if dashboard.html already exists in templates folder (and keep it)
          if [ -f "admin_panel/templates/dashboard.html" ]; then
            echo "Using existing dashboard.html template"
          elif [ -f "admin_panel/templates/dashboard" ]; then
            cp admin_panel/templates/dashboard admin_panel/templates/dashboard.html
          elif [ -f "admin_panel/dashboard.html" ]; then
            cp admin_panel/dashboard.html admin_panel/templates/dashboard.html
          else
            # Create a basic dashboard if not found
            echo "<!-- Basic Dashboard Template -->" > admin_panel/templates/dashboard.html
            echo '<h1>Minecraft Server Admin</h1><p>Setup your server configuration to begin.</p>' >> admin_panel/templates/dashboard.html
          fi
          
      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Launch admin panel
        run: |
          echo "Starting Minecraft Admin Panel..."
          
          # Create a basic CSS file if it doesn't exist
          if [ ! -f "admin_panel/static/css/style.css" ]; then
            echo "/* Minecraft Admin Panel CSS */" > admin_panel/static/css/style.css
            echo "body { font-family: Arial, sans-serif; }" >> admin_panel/static/css/style.css
          fi
          
          # Run the admin panel (Flask will keep running until terminated)
          python admin_panel.py
        env:
          ADMIN_PORT: ${{ github.event.inputs.port || '8080' }}
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          SECRET_KEY: ${{ secrets.ADMIN_SECRET_KEY || 'minecraft-default-secret' }}
          ADMIN_TIMEOUT_MINUTES: ${{ github.event.inputs.timeout || '60' }}
          
      - name: Start admin panel tunnel
        run: |
          cloudflared tunnel --url http://localhost:8080 > admin_tunnel.log 2>&1 &
          echo "Admin panel tunnel starting..."

      - name: Debug Cloudflared output
        run: |
          cloudflared tunnel --url http://localhost:8080 > tunnel.log 2>&1 &
          sleep 10
          cat tunnel.log

      - name: Start game server tunnels (for each server)
        run: |
          # For each Minecraft server port (e.g., 25565, 25566)
          cloudflared tunnel --url tcp://localhost:25565 > game_tunnel1.log 2>&1 &
          cloudflared tunnel --url tcp://localhost:25566 > game_tunnel2.log 2>&1 &
          echo "Game server tunnels starting..."

      - name: Extract tunnel URLs
        run: |
          sleep 5  # Give tunnels time to establish
          grep -o 'https://.*\.trycloudflare.com' admin_tunnel.log > tunnel_url.txt || echo "Admin tunnel not found"
          grep -o 'tcp://.*\.trycloudflare.com' game_tunnel1.log || echo "Game tunnel 1 not found"
          grep -o 'tcp://.*\.trycloudflare.com' game_tunnel2.log || echo "Game tunnel 2 not found"
          
          # Extract the admin panel URL
          ADMIN_URL=$(cat tunnel_url.txt)
          if [ ! -z "$ADMIN_URL" ]; then
            echo "Admin Panel URL: $ADMIN_URL"
            
            # Update the README.md file with the URL
            if [ -f "README.md" ]; then
              # Create a temporary file with updated content
              grep -v "ADMIN PANEL URL:" README.md > README.tmp
              echo "" >> README.tmp
              echo "## Quick Access" >> README.tmp
              echo "" >> README.tmp
              echo "✨ **ADMIN PANEL URL:** $ADMIN_URL ✨" >> README.tmp
              echo "" >> README.tmp
              echo "_(This URL is temporary and valid only while the workflow is running)_" >> README.tmp
              
              # Replace the original README
              mv README.tmp README.md
              
              # Commit the updated README if we have permissions
              if [ ! -z "${{ secrets.MY_PAT }}" ]; then
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git add README.md
                git commit -m "Update README with admin panel URL [skip ci]" || echo "No changes to commit"
                git push
              fi
            else
              echo "## Minecraft Server Admin Panel" > README.md
              echo "" >> README.md
              echo "✨ **ADMIN PANEL URL:** $ADMIN_URL ✨" >> README.md
              
              # Commit the new README if we have permissions
              if [ ! -z "${{ secrets.MY_PAT }}" ]; then
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git add README.md
                git commit -m "Create README with admin panel URL [skip ci]" || echo "No changes to commit"
                git push
              fi
            fi
          fi

      - name: Check for shutdown request
        run: |
          if [ -f "SHUTDOWN_REQUESTED" ]; then
            echo "Shutdown requested, terminating workflow"
            exit 0
          fi

      - name: Start Admin Panel with tmate
        uses: mxschmitt/action-tmate@v3
        if: ${{ hashFiles('SHUTDOWN_REQUESTED') == '' }}
        with:
          limit-access-to-actor: true