name: Minecraft Admin Panel

on:
  workflow_dispatch:
    inputs:
      port:
        description: 'Admin panel port'
        default: '8080'
        required: false

jobs:
  run-admin-panel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pyngrok requests
          
      - name: Download latest backups
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: minecraft-backup
          path: .
          
      - name: Ensure template directory
        run: mkdir -p templates
          
      - name: Create dashboard template
        run: |
          cat << 'EOF' > templates/dashboard.html
          <!-- Copy template HTML here -->
          EOF
          
      - name: Launch admin panel
        run: python admin_panel.py
        env:
          ADMIN_PORT: ${{ github.event.inputs.port || '8080' }}
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.repository }}
          SECRET_KEY: ${{ secrets.ADMIN_SECRET_KEY }}