name: Bedrock Minecraft Server

on:
  workflow_dispatch:
    inputs:
      server_id:
        description: 'Server ID'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Prepare server directory
        run: mkdir -p servers/${{ inputs.server_id }}

      - name: Download Bedrock server if missing
        run: |
          cd servers/${{ inputs.server_id }}
          if [ ! -f "bedrock_server" ]; then
            curl -o bedrock-server.zip "https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.41.01.zip"
            unzip -o bedrock-server.zip
            chmod +x bedrock_server
            rm bedrock-server.zip
          fi

      - name: Copy server_helper.py
        run: cp server_helper.py .

      - name: Initialize server (generate files only)
        run: python3 -u server_helper.py ${{ inputs.server_id }} bedrock true

      - name: Commit generated files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add servers/${{ inputs.server_id }}
          git commit -m "Update server files for ${{ inputs.server_id }}" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Start server and tunnel
        run: |
          python3 -u server_helper.py ${{ inputs.server_id }} bedrock
        # This will run continuously until the workflow times out or is canceled