name: Vanilla Minecraft Server

on:
  workflow_dispatch:
    inputs:
      server_id:
        description: 'Server ID'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare server directory
        run: mkdir -p servers/${{ inputs.server_id }}

      - name: Download server jar if missing
        run: |
          cd servers/${{ inputs.server_id }}
          if [ ! -f server.jar ]; then
            curl -o server.jar "https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar"
          fi

      - name: Accept EULA
        run: echo "eula=true" > servers/${{ inputs.server_id }}/eula.txt

      - name: Start server (first run generates files)
        run: |
          cd servers/${{ inputs.server_id }}
          java -Xmx2G -Xms2G -jar server.jar nogui || true

      - name: Commit generated files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add servers/${{ inputs.server_id }}
          git commit -m "Update server files for ${{ inputs.server_id }}" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}