name: Minecraft Server

on:
  workflow_dispatch:
    inputs:
      server_id:
        description: 'Server ID'
        required: true
      action:
        description: 'Action (start/stop)'
        required: true
        default: 'start'

jobs:
  run-minecraft-server:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hours max
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download server jar if needed
        run: |
          mkdir -p servers/${{ inputs.server_id }}
          if [ ! -f servers/${{ inputs.server_id }}/server.jar ]; then
            wget -O servers/${{ inputs.server_id }}/server.jar https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar
          fi
          
      - name: Run server
        run: python server_helper.py ${{ inputs.server_id }} ${{ inputs.action }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}